name: Python Test Suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Replace with the Python version you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
       # pip install -r requirements.txt  # Install from your requirements file

    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover -s test # For unittest
        # or
        # pytest  # For pytest
    - name: Report coverage
    
      run: |
        coverage report
